[project]
name = "ai-remote-dev-base"
version = "0.1.0"
description = "Base template to develop LLM apps on the cloud"
readme = "README.md"
authors = ["Suraj M S"]
requires-python = "==3.12.*"
dependencies = [
    "open-webui>=0.6.5",
]
